name: carousel_pro_nullsafety
description: carousel_pro 空安全版本
version: 2.0.0
homepage: https://github.com/jlouage/flutter-carousel-pro

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
